version: '3'

services:

  app:
    container_name: dynamic-user-segmentation-service
    build:
      context: .
      dockerfile: dynamic-user-segmentation-service.dockerfile
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: 'postgres'
    env_file:
      - .env
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped

volumes:
  pg-data:
